version: "2"
services:
  web:
    image: nginx
    container_name: web_service
    ports:
      - 8000:80
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - lo
  php:
    build: .
    networks:
      - lo
    depends_on:
      - db
  db:
    image: mysql:5.7.44
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - lo
networks:
  lo:
    driver: bridge